[package]
# we don't include some metadata to avoid accidental publishes
name = "test_no_warnings"
version = "0.0.0"
build = "build.rs"

[lib]
path = "lib.rs"

[build-dependencies]
gl_generator = { path = "../../gl_generator" }
