language: rust

install:
  # libxml2
  - sudo apt-get install libxml2
  # glfw
  - sudo apt-get install libXxf86vm-dev
  - git clone https://github.com/glfw/glfw.git
  - cd glfw
  - git checkout 3.0.3
  - cmake -DBUILD_SHARED_LIBS=ON .
  - make
  - sudo make install
  - cd ..
