before_install:
  - yes | sudo add-apt-repository ppa:hansjorg/rust
  - sudo apt-get update
install:
  - sudo apt-get install rust-nightly
script:
  - rustpkg install github.com/bjz/sax-rs
  - rustc -L .rust/build/*/github.com/bjz/sax-rs/ src/generator/main.rs
#  - rustpkg build generator
  - rustpkg build gl
