[package]
name = "gl_common"
version = "0.0.4"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
description = "Common glue for libraries using gl-rs"
license = "Apache-2.0"

[dependencies]
libc="*"
