[package]
name = "gl"
version = "0.5.1"
authors = ["Brendan Zabarauskas <bjzaba@yahoo.com.au>",
        "Corey Richardson",
        "Arseny Kapoulkine"
]
description = "OpenGL bindings"
license = "Apache-2.0"
build = "build.rs"
repository = "https://github.com/bjz/gl-rs/"

[build-dependencies]
gl_generator = { version = "0.4.0", path = "../gl_generator" }
khronos_api = { version = "1.0.0", path = "../khronos_api" }

[dev-dependencies]
glutin = "0.4"
