example = []

[package]
name = "gl"
version = "0.0.9"
authors = ["Brendan Zabarauskas <bjzaba@yahoo.com.au>",
        "Corey Richardson",
        "Arseny Kapoulkine"
]
description = "OpenGL bindings"
license = "Apache-2.0"
build = "build.rs"
repository = "https://github.com/bjz/gl-rs/"

[build-dependencies.gl_generator]
path = "../gl_generator"
version = "*"

[build-dependencies.khronos_api]
path = "../khronos_api"
version = "0.0.5"

[dependencies.gl_common]
path = "../gl_common"
version = "0.0.4"

[dependencies]
libc = "*"

#[dev-dependencies.glfw]
#git = "https://github.com/bjz/glfw-rs"
